<Project Sdk="Uno.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0-android;net10.0-ios;net10.0-browserwasm;net10.0-desktop;net10.0</TargetFrameworks>

    <OutputType>Exe</OutputType>
    <UnoSingleProject>true</UnoSingleProject>

    <AssemblyName>MSAVA_App</AssemblyName>
    <RootNamespace>MSAVA_App</RootNamespace>

    <!-- Display name -->
    <ApplicationTitle>MSAVA</ApplicationTitle>
    <!-- App Identifier -->
    <ApplicationId>MSAVA</ApplicationId>
    <!-- Versions -->
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <!-- Package Publisher -->
    <ApplicationPublisher>markinatorina</ApplicationPublisher>
    <!-- Package Description -->
    <Description>MSAVA powered by Uno Platform.</Description>

    <!--
      UnoFeatures let's you quickly add and manage implicit package references based on the features you want to use.
      https://aka.platform.uno/singleproject-features
    -->
    <UnoFeatures>
      Dsp;
      MediaElement;
      Hosting;
      Toolkit;
      Logging;
      LoggingSerilog;
      MVUX;
      Configuration;
      Http;
      Serialization;
      Localization;
      Authentication;
      Navigation;
      ThemeService;
      SkiaRenderer;
    </UnoFeatures>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug' or '$(IsUiAutomationMappingEnabled)'=='True'">
    <IsUiAutomationMappingEnabled>True</IsUiAutomationMappingEnabled>
    <DefineConstants>$(DefineConstants);USE_UITESTS</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(CI)'=='true'">
    <TargetFrameworks>net10.0</TargetFrameworks>
  </PropertyGroup>
    
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="System.Security.Cryptography.Xml" />
    <PackageReference Include="Tmds.DBus.Protocol" />
    <PackageReference Include="WinUI.TableView" />
  </ItemGroup>
    
  <ItemGroup>
    <ProjectReference Include="..\MSAVA-Shared\MSAVA-Shared.csproj" />
  </ItemGroup>
    
  <ItemGroup>
    <Compile Update="Presentation\FileManagement\FileManagementPage.xaml.cs">
      <DependentUpon>FileManagementPage.xaml</DependentUpon>
    </Compile>
  </ItemGroup>
    
  <ItemGroup>
    <Page Update="Presentation\FileManagement\FileManagementPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

</Project>
